###get all products
GET http://localhost:5000/product-api/products

###create product
POST http://localhost:5000/product-api/products
Content-Type: application/json

{
    "productName": "Ear buds",
    "price": 5000,
    "brand": "Realme"
}

###get all users
GET http://localhost:5000/user-api/users

###create user 
POST http://localhost:5000/user-api/users
Content-Type: application/json

{
    "name": "chethana",
    "email": "cheth@gmail.com",
    "password": "chethu@123",
    "cart": []
}

###add product to cart
PUT  http://localhost:5000/user-api/user-cart/user-id/6981921e24e9f90cbf988f28/product-id/69818a9886d9718fa1ae42c0

###Read user by id
GET http://localhost:5000/user-api/users/698175bab46a0cdd7566c27c

###comapring ids
GET http://localhost:5000/user-api/compare/69818a9886d9718fa1ae42c0